### ISSUE TITLE
horiontal bar chart option

### ISSUE THREAD

**Issue by MatthiVH** [ResidentMario/missingno#102]
Hi,

Is there a way to plot the vertical bar charts in the matrix- or bar-funtion as a horizontal bar chart instead of a vertical one? I was searching through the code but I'm not sure if it's possible to post-process this using matplotlib functions? Could this be added as an (post-processing) option?
Anyway great package, I love it.

Matthias

**Comment by ResidentMario** [comment]
Hi, `dendrogram` does support an `orientation` parameter but no such thing is implemented for `matrix` or for `bar`. It's an interesting idea; would be pretty easy to do with `bar` and pretty hard to do with `matrix`. Will leave this open as a feature request.

**Comment by ResidentMario** [comment]
Oh wow actually it looks like someone made an unfinished PR for this about a year ago that I completely forgot about: #94.
