### ISSUE TITLE
No way to extract values from matplotlib charts 

### ISSUE THREAD

**Issue by lodowner** [ResidentMario/missingno#108]
It would be really useful if it were possible to extract the following from bar() or matrix():

a) A df or array of the names of all the columns with missing data from 
b) A df or array of the % of data completness as show on y-axis of bar()

Is it possible to do this?
I attempted this using various matplotlib methods but to no avail.

**Comment by ResidentMario** [comment]
Hi, these are best done using `pandas` operations. Look into [`pandas.DataFrame.isnull`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isnull.html).
