### ISSUE TITLE
missingno in PyCharm

### ISSUE THREAD

**Issue by Abe92** [ResidentMario/missingno#113]
Hi,

I just recently (on 8th July 2020) installed this library in my PyCharm.
However, whenever I try to use it the PyCharm won't show me the nice graphical representation of the missing data.

![missingno_1](https://user-images.githubusercontent.com/9216743/86907194-944c0600-c10c-11ea-808d-9fd4a7771d70.JPG)
![missingno_2](https://user-images.githubusercontent.com/9216743/86907201-9615c980-c10c-11ea-9212-198f1ba48be0.JPG)

Is this currently not supported in PyCharm?

*Edit: 
(1) I have included some screenshots on 8th July 2020

**Comment by atnac8** [comment]
I think you need to use matplotlib to actually plot the AxesSubplot object
So first `import matplotlib.pyplot` and after using `msno.matrix()` (without the print) call `plt.show()`

**Comment by Abe92** [comment]
> I think you need to use matplotlib to actually plot the AxesSubplot object
> So first `import matplotlib.pyplot as plt` and after using `msno.matrix()` (without the print) call `plt.show()`

Thanks, Atnac8!
It did work.

Many thanks for your time!
