### ISSUE TITLE
Incorporate example dataset

### ISSUE THREAD

**Issue by arturomoncadatorres** [ResidentMario/missingno#114]
First of all, thank you for such a useful, neat, little package!

Having a base dataset is very handy for showcasing and testing `missingno`. I see that originally [it uses the `collisions` dataset](https://github.com/ResidentMario/missingno#quickstart-). Unfortunately, to get the dataset, you need additional steps (i.e., pip install `quilt`).

I think it would be more practical to have such dataset as part of `missingno` itself like, for instance, on top of my head, [lifelines does](https://lifelines.readthedocs.io/en/latest/Quickstart.html#kaplan-meier-nelson-aalen-and-parametric-models). What do you think?

**Comment by ResidentMario** [comment]
Hi, yes, I will probably eventually move to a specific submodule for example data, similar to what I did with `geoplot`. This has been a low priority because what's there now works.

**Comment by arturomoncadatorres** [comment]
Great. If I can give a hand, let me know :wink:

**Comment by ResidentMario** [comment]
Done now
