### ISSUE TITLE
no attribute 'matrix'

### ISSUE THREAD

**Issue by linlin860320** [ResidentMario/missingno#115]
When I run my code, theres an error, my code is below:

`import missingno as msno`
`import pandas as pd`

`data = pd.read_csv('xxx.csv')`
`msno.matrix(data, labels=True)`

And then I got this error:
**AttributeError: module 'missingno' has no attribute 'matrix'**

but I won't find the solution on google. can anyone give me some advice that how to fix it, and why has this error

**Comment by ResidentMario** [comment]
Try `pip install -U missingno`.

**Comment by linlin860320** [comment]
I had try your cmd, but the error still exist.
I try to uninstall missingno first, and then use your cmd install.

**Comment by ResidentMario** [comment]
Closing as stale
