### ISSUE TITLE
error in matrix function at line 117 - caused by line 185

### ISSUE THREAD

**Issue by armando-fandango** [ResidentMario/missingno#116]
If the dataset has timestamps starting from middle of the day or ending with middle of the day then trying to divide by Day or Hour causes error. Sending through a fix.

**Comment by ResidentMario** [comment]
I've merged your PR. Thanks for the fix! Note that it may be a while before I get around to minting a release, however.

**Comment by armando-fandango** [comment]
Thanks, no problem for the release, as I can use from the github for now.

**Comment by ResidentMario** [comment]
New release coming out today
