### ISSUE TITLE
Simplify what exactly -1,0,1 in Heatmap?

### ISSUE THREAD

**Issue by Jainu-s** [ResidentMario/missingno#126]
I have gone through the documentation but I'm not getting exactly what 1, 0, -1 represent in heatmap. Please explain in a simplified manner.

**Comment by ResidentMario** [comment]
-1 is perfect negative correlation, 1 is perfect positive correlation, 0 is random relationship. This visualization at the top of the Wikipedia page on [correlation](https://en.wikipedia.org/wiki/Correlation_and_dependence) is a good visual summary.
