### ISSUE TITLE
Add legend/labeling to graphs

### ISSUE THREAD

**Issue by tomshaffner** [ResidentMario/missingno#129]
The graphs on the example page are vague as to whether the indicators are for present or missing data. The library name would lead one to believe that the black sections might be missing data, and it's only on reading the accompanying text/description that it's clear that the reverse is true.

A simple legend or label of some sort should be added to the graphs indicating which colors are missing data vs. present data. Without this, the only way for graphs made elsewhere to be clear is for users to track back to the descriptions on the example page here or check manually, which rather defeats the purpose of the library.

Otherwise fantastic library; thanks so much for your great work!

**Comment by ResidentMario** [comment]
Thanks for submitting this idea! However, to be honest, I don't think this is pressing. This package has been around for five years now, and you're the only person to have ever reported this confusion thus far.

I think you're right that some people are briefly confused which is which, but I also think it's reasonable to have them to read the docs or docstrings to clear up that confusion. I also think that the plots are busy enough as it is&mdash;reserving space for a legend would clutter the display and reduce the amount of data you can usefully fit in the plot.

If you absolutely must have a legend, this is easily-enough done by building your own and attaching it to the plot using `matplotlib`.
