### ISSUE TITLE
Regarding scipy<=0.13.0

### ISSUE THREAD

**Issue by lalvarezguillen** [ResidentMario/missingno#13]
Hello ResidentMario! Great project and great project&user names!

I ran into issues using missingno with scipy.**version** <= 0.13.0.  It turns out in those versions scipy.cluster.hierarchy.dendrogram doesn't take ax as a kwarg, thus breaking up when trying to plot a dendrogram with missingno.
And I noticed that dependency version issue isn't pointed out anywhere. Maybe there's a place for it in setup.py?

Keep it up!

**Comment by ResidentMario** [comment]
Thanks for the report. `scipy 0.13.0` is a relatively old version of `scipy`, which appears to currently be on version `0.18`. Hence why I didn't know where the breakage occurs.

I don't see a change to that `ax` argument in the `0.13.1` [patch notes](http://docs.scipy.org/doc/scipy/reference/release.0.13.1.html). Perhaps you meant `<0.13.0` ([patch notes](http://docs.scipy.org/doc/scipy/reference/release.0.13.0.html))?

I'll take a look at adding version dependencies to `setup.py`. Need to get to the other issues for this repo too.

**Comment by lalvarezguillen** [comment]
Hey ResidentMario! Sorry if I worded it wrong somehow. I believe the issue boils down to this:

0.13.0 doesn't take ax kwarg: https://github.com/scipy/scipy/blob/1cc8beed5362ed290f5a8ddf4e99db49b4de6286/scipy/cluster/hierarchy.py#L1687

0.18.0 takes ax kwarg: https://github.com/scipy/scipy/blob/master/scipy/cluster/hierarchy.py#L1776

0.14.0b1 is the first appearance of the ax kwarg I could find: https://github.com/scipy/scipy/blob/9dc196c81e82551884d8d7adc8ac5b0de80c3ea4/scipy/cluster/hierarchy.py#L1687

**Comment by ResidentMario** [comment]
I'm going to go ahead and close this as being too far gone in the past. You really shouldn't be using versions of `scipy` this old anymore, TBH.
