### ISSUE TITLE
heatmap and dendrogram do not plot

### ISSUE THREAD

**Issue by ElMoe** [ResidentMario/missingno#133]
Hi,
when using heatmap and dendrogram, I get the following error:
`C:\Users\USER\anaconda3\lib\site-packages\seaborn\matrix.py:311: UserWarning: Attempting to set identical left == right == 0 results in singular transformations; automatically expanding.
  ax.set(xlim=(0, self.data.shape[1]), ylim=(0, self.data.shape[0]))
C:\Users\USER\anaconda3\lib\site-packages\seaborn\matrix.py:311: UserWarning: Attempting to set identical bottom == top == 0 results in singular transformations; automatically expanding.
  ax.set(xlim=(0, self.data.shape[1]), ylim=(0, self.data.shape[0]))`

In result there is just the color Y-axis plotted (for the heatmap) and column names vs. Y-axis (for the dendrogram).

I have a fresh anaconda installed here with:

***INSTALLED VERSIONS***
------------------
commit           : db08276bc116c438d3fdee492026f8223584c477
python           : 3.8.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : de_DE.cp1252

pandas           : 1.1.3
numpy            : 1.19.2
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.4
setuptools       : 50.3.1.post20201107
Cython           : 0.29.21
pytest           : 6.1.1
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : 1.3.7
lxml.etree       : 4.6.1
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.19.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.8.3
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : 2.7.1
odfpy            : None
openpyxl         : 3.0.5
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.2
sqlalchemy       : 1.3.20
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 1.2.0
xlwt             : 1.3.0
numba            : 0.51.2`

All the code in the jupyter notebook is:
`import pandas as pd
import missingno as msno
df3 = pd.read_csv('small.csv')
ax=msno.heatmap(df3)`

The NYC car crash data works perfectly.

Here are 20 rows of my csv:
`,DATETIME,Distance,Power,Liter,V1,V2,X,Y,Phase,Phase_compressed,Production
2844,2021-03-31 08:08:26,20.0625,3575.3,0,1,1,2.62337,1.99048,13,2,0
1505,2021-03-31 07:34:58,20.0625,3186.76,0,0,1,3.05117,1.6845599999999998,7,1,0
7114,2021-03-31 09:48:01,20.0625,2296.93,0,1,1,0.802541,1.30454,21,5,1
7451,2021-03-31 09:57:34,20.0625,-4438.99,63,1,1,3.8524300000000005,0.845234,21,5,1
3535,2021-03-31 08:23:28,20.0625,577.3530000000001,0,0,1,2.79183,3.88697,13,2,0
5142,2021-03-31 08:58:53,20.0625,1550.66,0,1,1,3.65956,1.68308,13,2,0
3000,2021-03-31 08:11:48,20.0625,566.42,0,1,1,3.65965,0.940075,13,2,0
9641,2021-03-31 10:49:39,20.0625,-3410.29,64,1,1,3.93245,1.3029700000000002,21,5,1
4410,2021-03-31 08:42:48,20.0625,-363.57,0,0,1,1.81529,1.78217,20,4,0
2538,2021-03-31 08:01:03,20.0625,727.92,0,0,1,4.09127,0.47963,12,2,0
6258,2021-03-31 09:25:07,20.0625,2980.79,0,1,1,2.56127,2.2528799999999998,20,4,0
6715,2021-03-31 09:39:02,20.0625,2406.15,0,0,0,0.797337,0.263776,21,5,1
1333,2021-03-31 07:30:55,20.0625,3205.49,0,0,0,1.05243,0.535762,4,1,0
7951,2021-03-31 10:08:34,20.0625,-250.44,64,1,1,3.8936300000000004,0.629215,21,5,1
6907,2021-03-31 09:43:15,20.0625,1556.12,0,1,1,0.15029700000000001,1.6450799999999999,21,5,1
33,2021-03-31 06:59:25,20.0625,3255.03,0,0,0,3.3091199999999996,2.1511299999999998,20,4,0
9798,2021-03-31 10:53:20,20.0625,1315.43,0,1,1,3.00236,1.1917,21,5,1
9926,2021-03-31 10:56:48,20.0625,1537.79,0,0,1,4.10165,0.912452,21,5,1
7310,2021-03-31 09:52:40,20.0625,-3402.1,0,1,1,3.87198,1.1840000000000002,21,5,1
2438,2021-03-31 07:58:53,20.0625,2352.33,0,0,1,4.182580000000001,0.332945,12,2,0`

Can you help?

Best regards,
B.

**Comment by ResidentMario** [comment]
Closing as stale. Hope you fixed your issue! You data doesn't include any null values, as far as I can tell, which is probably what the problem was.
