### ISSUE TITLE
geoplot function still in code after issue #59, how to refactor?

### ISSUE THREAD

**Issue by datatalking** [ResidentMario/missingno#136]
I like the missingno and want to incorporate it into a project so this will be helpful. When I run it in the provided binder (which was very helpful) on cell #8 it gives an error that has been identified in issue #59 but i'm not seeing the code was refactored, I am referring to the **quickstart binder**.

geoplot function would not work for me #59, again this was mentioned in issue #60 and I see the README.md comments but the code as of today is still calling msno.geoplot.

Error
/home/jovyan/missingno/missingno.py:495: UserWarning: The 'geoplot' function has been deprecated, and will be removed in a future version of missingno. The 'geoplot' package has an example recipe for a more full-featured geospatial nullity plot: https://residentmario.github.io/geoplot/gallery/plot_san_francisco_trees.html
  "The 'geoplot' function has been deprecated, and will be removed in a future version "

I tried changing
msno.geoplot(collisions, x='LONGITUDE', y='LATITUDE'

to
msno.aggplot(collisions, x='LONGITUDE', y='LATITUDE')

Can I refactor this for you?
Let me know what needs to be swapped, and thanks again for making and sourcing a great tool!!

**Comment by ResidentMario** [comment]
Hi, I pushed a PR just now that removes `geoplot` from the codebase. If you need that functionality, check out `quadtree` in the [`geoplot` package](https://residentmario.github.io/geoplot/index.html) instead.
