### ISSUE TITLE
source-file for pypi?

### ISSUE THREAD

**Issue by brobr** [ResidentMario/missingno#145]
Hi the github source file does not compile with
`python3 setup.py  install '

Could you please publish a source file on pypi.org that does? (I am not using  the whl file)

**Comment by DrRadan** [comment]
I am trying to install with pip3 install and it get's stuck. When will python3 be supported?

**Comment by brobr** [comment]
It is compiling for me on 3.9.10 (maybe 3.10 gives problems? My OS, SLackware, reverted from that to 3.9, too many problems at the time.)

**Comment by ResidentMario** [comment]
Installs just fine for me from source via `python setup.py install` in a fresh `conda` environment with Python 3.10 installed.

@DrRadan If `pip3` gets stuck, that's likely [the dependency resolver getting stuck](https://pip.pypa.io/en/stable/topics/dependency-resolution/).
