### ISSUE TITLE
Add title option

### ISSUE THREAD

**Issue by TomerAntman** [ResidentMario/missingno#149]
Adding a title parameter to the various figures should be rather easy and will help to make sense if many figures are created for multiple datasets

**Comment by ResidentMario** [comment]
TBH I don't think a title parameter is necessary because it's so easy to do using `matplotlib`:

```python
ax = msno.matrix(df)
ax.set_title("My Title")
```

**Comment by TomerAntman** [comment]
I tried that but it makes the line on the side disapear
