### ISSUE TITLE
Basic tabular findings for columns 

### ISSUE THREAD

**Issue by MRaahulVignesh** [ResidentMario/missingno#156]
Hello ppl, 
I was just wondering if this basic function can be added to the package. On providing a df, it will provide the number of missing values and percentage of missing values column-wise or row-wise in a tabular form?

something like this (the first column would mention the column names or row names)

<img width="212" alt="Screenshot 2022-06-08 at 12 56 12 PM" src="https://user-images.githubusercontent.com/41645355/172705769-63cc8304-7205-4397-a015-090a53b308bd.png">

though it was basic, i was using this multiple times in my code and felt that it would be a good addition to the package.

if it can be added, i would like to contribute to this. Thank you.

**Comment by ResidentMario** [comment]
This package used to include certain numeric functions. I removed them because they weren't very useful. Individuals need to make their own decisions on what to classify as missing or not missing, there's no one function that can do it all.
