### ISSUE TITLE
MatplotlibDeprecationWarning - grid(b=False) -> grid(visible=False)

### ISSUE THREAD

**Issue by r-leyshon** [ResidentMario/missingno#161]
Running pytest results in:

MatplotlibDeprecationWarning: The 'b' parameter of grid() has been renamed 'visible' since Matplotlib 3.5; support for the old name will be dropped two minor releases later.
    ax0.grid(b=False)

**Comment by sernst** [comment]
Matplotlib 3.7 has been released now and has dropped the 'b' parameter as @r-leyshon mentioned it would above. This is now causing errors instead of deprecation warnings:

![Snag_b5bdcd29](https://user-images.githubusercontent.com/451936/219040916-a91e2081-378e-48b1-955e-6d6045e77e2b.png)

**Comment by r-leyshon** [comment]
To confirm @sernst observation, now missingno breaks my build checks if I do not pin matplotlib to 3.5.0. 

Please consider the PR I raised. It should be a one liner to fix I think. Link to the breaking change in [matplotlib changelog](https://matplotlib.org/stable/api/prev_api_changes/api_changes_3.5.0.html#the-first-parameter-of-axes-grid-and-axis-grid-has-been-renamed-to-visible)

**Comment by ale-dg** [comment]
Hi all,

Just a quick FYI, I have installed the library now through conda (condo-forge) and the issue is still built in that distribution. It is not a big issue to solve if one is familiar with matplotlitb, though it might open an issue if someone is not so familiar with working it around.

Best
