### ISSUE TITLE
Module loading error

### ISSUE THREAD

**Issue by ishita199615** [ResidentMario/missingno#165]
Despite installing the package under the base in Anaconda. Still, I am getting a module not found error when importing it. 
<img width="1049" alt="Screen Shot 2023-05-24 at 9 08 13 AM" src="https://github.com/ResidentMario/missingno/assets/49127145/25439824-474b-4770-9c34-e7cbd07b2b43">

**Comment by ResidentMario** [comment]
This is always user error.
