### ISSUE TITLE
Plotly / Dash implementation option

### ISSUE THREAD

**Issue by Robin66014** [ResidentMario/missingno#166]
As me and co-researchers are trying to implement the graph in a Dash webapplication, it would be nice to be able to plot the graphs as plotly figures, so that they are interactive (and you can see exactly which points are missing), and uploadable to Dash.

**Comment by ResidentMario** [comment]
`missingno` is solidly a `matplotlib` thing and will stay that way.

It shouldn't be impossible to extract the core ideas and reimplement them in Dash, though. But that would be a separate project. 🙂
