### ISSUE TITLE
Nullity == nan?

### ISSUE THREAD

**Issue by adamkgoldfarb** [ResidentMario/missingno#18]
Dumb question (and yes there are those, and yes this is one): is NaN (np.nan) considered a nullity in missingno? 

Thanks for the great work on this-- and on other Resident Mario jams!

**Comment by ResidentMario** [comment]
Short answer: yes.

Longer answer: `missingno` reads `pandas.DataFrame` input, and `pandas` automatically encodes missing data into `np.nan` (and converts `None -> np.nan` also). `missingno` then uses [`pd.isnull`](https://github.com/pandas-dev/pandas/blob/v0.19.1/pandas/types/missing.py#L27-L45) to determine nullity.

[I wrote a blog post (partially) on this subject a while ago that ought to be worth reading](http://www.residentmar.io/2016/06/12/null-and-missing-data-python.html).

**Comment by adamkgoldfarb** [comment]
Great-- just wanted to confirm that anything coded to np.nan would be picked up by missingno. Thanks again.
