### ISSUE TITLE
Option to remove the sparkline

### ISSUE THREAD

**Issue by nipunbatra** [ResidentMario/missingno#2]
Hi,
Many thanks for the awesome work! When the number of rows is large, the sparkline looks less useful (more difficult) to visually understand the #features available just looking at it. Wondering if an option to toggle the sparkline off could be added.

**Comment by ResidentMario** [comment]
I actually took a quick look at that already. The current view relies on the `matplotlib` grid engine and I couldn't find, admittedly on cursory examination, an easy way to toggle it.

This is definitely on my to do list though.

**Comment by nipunbatra** [comment]
I'm sorry I didn't clarify. I meant an option to not use the sparkline at all. So, that'd mean to use only `ax0` in your code, and don't add `ax1`. Ofcourse, the `gridspec` will need to be changed from (1,2) to (1,1).

**Comment by ResidentMario** [comment]
Addressed prior to 3a5420e.
