### ISSUE TITLE
Matplotlib error: 'AxesSubplot' object has no attribute 'set_facecolor'

### ISSUE THREAD

**Issue by noelmas** [ResidentMario/missingno#25]
Get this error when running msno.matrix on a standard Pandas DataFrame. 

I'm using:

Using:

matplotlib.__version__
'1.5.1'

pd.__version__
'0.19.2'

Here's the rest of the error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-e5e39db43960> in <module>()
----> 1 msno.matrix(companies.sample(100))

/Users/Sam/anaconda/lib/python3.5/site-packages/missingno/missingno.py in matrix(df, filter, n, p, sort, figsize, width_ratios, color, fontsize, labels, sparkline, inline, freq)
    250         ax1.grid(b=False)
    251         ax1.set_aspect('auto')
--> 252         ax1.set_facecolor((1, 1, 1))
    253         # Remove the black border.
    254         ax1.spines['top'].set_visible(False)

AttributeError: 'AxesSubplot' object has no attribute 'set_facecolor'

**Comment by ResidentMario** [comment]
`matplotlib 2.0.0` deprecated `set_axis_bgcolor` and replace it with `set_facecolor`. In my [patch for mpl 2.0.0 compatibility](https://github.com/ResidentMario/missingno/commit/61e4af8cac60759b46b2f18fdf1d2805b468b6de) I didn't check to see whether or not `set_facecolor` exists in `mpl < 2.0.0`&mdash;my apologies, your error shows that it does not.

To maintain `mpl < 2.0.0` compatibility, I'm going to have to implement some kind of version check here. In the meanwhile, to fix this *right now* you should update your `matplotlib` to the latest version.

**Comment by ResidentMario** [comment]
Resolved in `0.3.5`. You can `pip install -U missingno` to upgrade.

**Comment by noelmas** [comment]
Heroic project by the way, really making the early stages of my data exploration much more efficient. Thank you @ResidentMario
