### ISSUE TITLE
Return axes object instead of the figure when inline=False

### ISSUE THREAD

**Issue by 1x0r** [ResidentMario/missingno#26]
I am trying to make a subplot grid 2x2 with four `msno.matrix(..., inline=False)`, but it requires an `axes` object. 
Is there any workaround or is it possible to add/change the behavior of the plotting function to return `axes`?

**Comment by ResidentMario** [comment]
Yes, the proper behavior would be to return ax so that it doesn't overwrite the figure. TODO.

**Comment by ResidentMario** [comment]
Does 61f084f199 (live in `0.3.6`; `pip install missingno --upgrade` to get the latest) address this issue?
