### ISSUE TITLE
Saving output as .bmp

### ISSUE THREAD

**Issue by Arty2** [ResidentMario/missingno#28]
This is most likely a very Python newbie question, but unfortunately I haven't managed to get it working: how does one save the output to an image file?

**Comment by ResidentMario** [comment]
Sorry, missed this. The underlying plot is a `matplotlib` object, so you should be able to do e.g. `ax = plt.gca()` and then run something like `plt.save_figure(format='bmp')`.

Although whether or not you can save to a `BMP` file directly may depend on the backend. See [here](https://matplotlib.org/devdocs/api/_as_gen/matplotlib.pyplot.savefig.html).
