### ISSUE TITLE
Returning matplotlib.figure/axes?

### ISSUE THREAD

**Issue by nipunbatra** [ResidentMario/missingno#3]
Hi,
For users who want to fiddle around with the produced plot, it would be helpful to return the matplotllib.figure/axis. My use case- I want to give a ylabel to the rows to use in a publication.

**Comment by ResidentMario** [comment]
Ah, so instead of ending with `fig.show()`, something like ending with `plt.show(); return fig`? Good idea; I'll take a look at `seaborn` to see how it handles that.

**Comment by nipunbatra** [comment]
Yes, and it'll also allow a user to save the figure to a png or pdf.  Also, returning the figure will allow these plots to be interfaced with mpld3 and Plotly.

**Comment by ResidentMario** [comment]
Ok, so the default `seaborn` behavior is to both plot the figure and return a `matplotlib` object of some sort. However, I find this in-ideal, as the returned plot element's return statement pollutes the view:

![example](https://cloud.githubusercontent.com/assets/3466341/14227680/14ae6c24-f8d1-11e5-8289-5551db9bea8f.png)


Note the `<matplotlib.axes._subplots.AxesSubplot at 0x1147a0f0>`.

To overcome this in my current build I've added a `inline=True` argument which hooks into the following method ending:

    if inline:
        plt.show()
    else:
        return fig.axes

If `inline` is left alone `missingno` will draw the plot and no more.

If `inline` is set to `false` it will return the axes. Default `matplotlib` behavior will cause the plot to be drawn anyway though.

Do you think this is a good solution?

**Comment by ResidentMario** [comment]
Addressed prior to 3a5420e.
