### ISSUE TITLE
 min() arg is an empty sequence

### ISSUE THREAD

**Issue by crooks3184** [ResidentMario/missingno#37]
I have the following code, which has worked well up until today:

with PdfPages('Missing Data Report.pdf') as pdf:
    for segment in SegDict_H1.keys():
        matrix_fig = msno.matrix(SegDict_H1[segment],fontsize=12,inline=False)
        matrix_fig.text(0,1.5,'{0} Segment Missing Data Matrix'.format(segment),style='italic',
                                bbox = {'facecolor': 'blue','alpha':.25,'pad':10},fontsize=25)
        pdf.savefig(bbox_inches='tight',pad_inches = 0.25)
        plt.clf()
plt.close('all')

Executing this code provided me with a multipage .pdf file of a missing data matrix for each DataFrame in my Python dictionary.  Just today, however, this code is no longer working properly and I am getting errors that I do not know how to interpret.

**Comment by ResidentMario** [comment]
The code hasn't changed recently so this is most likely an issue in your
environment configuration.
