### ISSUE TITLE
Plot axes labels & naming issues

### ISSUE THREAD

**Issue by jsh9** [ResidentMario/missingno#38]
Your nullity plot is somewhat confusing: by common sense, "nullity" means "degree of null-ness", hence a nullity of 1 would indicate "all records being missing", but in your plot, nullity seems to have an opposite meaning?

Therefore, could you add Y axis labels to the plot (not only the nullity plot, but also other plots, if applicable). Thanks!

**Comment by ResidentMario** [comment]
I use nullity to mean that an individual field is missing, not that an entire record is present or absent. It's a slightly more nuanced definition that I only use in the `README` to help explain what the plots do. I don't expect users to hew to it pretty closely.

I don't see how y-axis labels would help with this, and they would clutter the display. Sorry, but this is a wontfix for me.
