### ISSUE TITLE
does not work with pandas v.21

### ISSUE THREAD

**Issue by epogrebnyak** [ResidentMario/missingno#39]
---------------------------------------------------------------------------
AttributeError Traceback (most recent call last)
<ipython-input-45-0497999b6ec3> in <module>()
----> 1 msno.matrix(dfa.asfreq('A'), freq='A')

~/anaconda3/lib/python3.6/site-packages/missingno/missingno.py in matrix(df, filter, n, p, sort, figsize, width_ratios, color, fontsize, labels, sparkline, inline, freq)
212 t.strftime('%Y-%m-%d'))
213 
--> 214 elif type(df.index) == pd.tseries.index.DatetimeIndex:
215 ts_array = pd.date_range(df.index.date[0], df.index.date[-1],
216 freq=freq).values

AttributeError: module 'pandas.tseries' has no attribute 'index'

**Comment by ResidentMario** [comment]
Welp, time for another new minor patch version.

**Comment by ResidentMario** [comment]
Fixed in the new `0.3.8` patch release (changed to `pd.DatetimeIndex`). Thanks for reporting this!

**Comment by epogrebnyak** [comment]
Many thanks for fixing this, we are updating the on new version.
