### ISSUE TITLE
what is the limit num of  pic

### ISSUE THREAD

**Issue by xxllp** [ResidentMario/missingno#42]
Hi,I have newer ，have an data of 2000+ missing feature , 
when I use msno.matrix  only have full blank 。So what is the max num  of pic

**Comment by ResidentMario** [comment]
For practical purposes, at usual display resolutions I suggest limiting it to 250 rows and around 50 columns.

You can technically include as many columns as you want, if you increase the size of the figure. E.g. the default `figsize` is `(25, 10)`, but you could fit twice as much data in there if you use, say, `(50, 10)`...the image will just be bigger.
