### ISSUE TITLE
Expand paper to conform to JOSS standards

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [ResidentMario/missingno#43]
See guidelines here: 
http://joss.theoj.org/about#author_guidelines

See example accepted papers here: 
http://joss.theoj.org/papers/accepted

**Comment by ResidentMario** [comment]
Paper expanded. I'll leave this issue open for now, though.

**Comment by Kevin-Mattheus-Moerman** [comment]
Thanks, looks a lot better. Here are some quick points on the paper. 
- [ ] Please work on adding references
- [ ] Fix type: "..easily to, at a glance, understanding patterns..." should probably be: "...easily to, at a glance, understand patterns'''"
- [ ] Fix typo: "provides an methodology" should be : "provides a methodology"
- [ ] To me something feels odd/missing here due to the use of the word both: "The visualizations are consciously designed to be as effective as possible at uncovering missing data patterns both between columns of data, and hence, to help its users build more effective data models and pipelines."
- [ ] I suggest and recommend (since your package offers visualization), to add a figure which you could use as a "graphical summary" of what your package does.

**Comment by ResidentMario** [comment]
@Kevin-Mattheus-Moerman  I've put in figures for each of the functions. Hopefully that doesn't make it overlong?

**Comment by Kevin-Mattheus-Moerman** [comment]
@whedon generate pdf

**Comment by Kevin-Mattheus-Moerman** [comment]
The length is fine. Some of the typos are still present in the paper. To fix the references use `[@articleName]` to cite items in the paper. This will make them appear in the text and the reference list.

**Comment by ResidentMario** [comment]
They are? Damn, OK, thanks for the thoroughness, I'll go over it again. Maybe I've edited in new ones!

**Comment by Kevin-Mattheus-Moerman** [comment]
See tick boxes above. Its the "easily to.. understand". Should probably be "easy to.... understand".

**Comment by Kevin-Mattheus-Moerman** [comment]
Looks good now. Thanks.
