### ISSUE TITLE
Cite SciPy family of packages and seaborn

### ISSUE THREAD

**Issue by zkamvar** [ResidentMario/missingno#44]
The final sentence of your paper states:

> The underlying packages involved (numpy, pandas, scipy, matplotlib, and seaborn) are familiar parts of the core scientific Python ecosystem, and hence very learnable and extensible. missingno works "out of the box" with a variety of data types and formats, and provides an extremely compact API.

The packages numpy, pandas, scipy, matplotlib, and seaborn should be cited. You can use this link to find the appropriate citation methods: https://scipy.org/citing.html (for all but seaborn).

**Comment by zkamvar** [comment]
Note: this is related to the first item in https://github.com/ResidentMario/missingno/issues/43#issuecomment-361284523

**Comment by ResidentMario** [comment]
Think I have this covered now.
