### ISSUE TITLE
Add tests for nullity_filter and nullity_sort

### ISSUE THREAD

**Issue by zkamvar** [ResidentMario/missingno#46]
Since these functions return a pandas data frame, they can be tested for correctness. Please include a testing suite for these functions.

**Comment by zkamvar** [comment]
N.B. This also applies to helper functions such as [`_calculate_geographic_nullity()`](https://github.com/ResidentMario/missingno/blob/4230493677207ae8474f6e8f6a7adec4b528036a/missingno/missingno.py#L573-L589)

**Comment by ResidentMario** [comment]
Done. The `_calculate_geographic_nullity()` comment is no longer relevant because that methodology has been moved out of the package entirely (see discussion elsewhere).
