### ISSUE TITLE
Idea: Unit tests for dataviz function

### ISSUE THREAD

**Issue by rhiever** [ResidentMario/missingno#47]
I understand that it is difficult to write unit tests for dataviz functions because the output is visual. However, one possible way to write unit tests for dataviz functions is to provide the functions with fixed input, then take the output dataviz and save/hash/serialize it somehow. Then that saved/hashed/serialized can be compared to a known, correct saved/hashed/serialized output from before. That way the unit test will fire off if you change anything related to the plotting functionality.

**Comment by ResidentMario** [comment]
Done, now living at `viz_tests.py`.
