### ISSUE TITLE
Add badges to your README to show supported Python versions + software license

### ISSUE THREAD

**Issue by rhiever** [ResidentMario/missingno#49]
Badges are useful for showing the status of your project and related information in a quick, visual manner. I think it would be beneficial to list information such as the versions of Python supported by your project (2.7? 3.6?) and software license (MIT).

**Comment by ResidentMario** [comment]
Done in 51b67d. The Python versions badge isn't working, so I've just added that to the textual description.

**Comment by rhiever** [comment]
Does this badge work for you?

```
[![Python 3.6](https://img.shields.io/badge/python-3.6-blue.svg)](https://www.python.org/downloads/release/python-360/)
```

**Comment by ResidentMario** [comment]
Ah, right, I forgot you could specify arbitrary characters that way. I went ahead and added a `3.4+` badge, thanks.
