### ISSUE TITLE
option for grouping the columns by similarity?

### ISSUE THREAD

**Issue by EnricoGiampieri** [ResidentMario/missingno#5]
Hi, I like the idea of this package very much.
Would it be much of a work to implement an automatic grouping of the features (and maybe subjects) based on similarity?
this way one can see if the missing are random or there is some pattern...

**Comment by ResidentMario** [comment]
I thought about implement a feature diagram at the bottom of the plot, but deferred doing so because I thought it would be too overwhelming for a default feature, and also because I wanted to get something done and send it out in one weekend. =)

Still, this is a very good idea. I'm currently thinking about what sorts of options I want to enable (in addition to the issues posted earlier) on this plot, and about other plots that could potentially be useful for the purposes of missing data visualization.

**Comment by EnricoGiampieri** [comment]
I'm not sure if you considered it, but it might be worth using seaborn as a back end: it is dataframe aware, and will make everything simpler.
A plot similar to your can be implemented as

    import pylab as plt
    import pandas as pd
    import seaborn

    data = pd.DataFrame({'a':plt.randn(30), 'b':plt.randn(30), 'c':plt.randn(30)})
    data.values[data.values<-0.5] = plt.nan
    null_values = pd.isnull(data)
    seaborn.heatmap(null_values)

it does also have a clustermap figure, but it take the whole figure and does not allow you to include that spark plot you've done, but for reference I'll leave you the code.

    seaborn.clustermap(null_values, row_cluster=False)

**Comment by ResidentMario** [comment]
My first attempt was in `seaborn`, actually. The result was *OK*, but I didn't find the `seaborn` framework to be extensible enough for my purposes. It's not really meant to be anyway---use the underlying `matplotlib` at that point!

**Comment by ResidentMario** [comment]
I used the `scipy` hierarchical clustering feature to generate a categorical dendogram of column features by completion correlation. I'm thinking of including it both as an optional feature of the current chart and as a new `dendogram` chart option.

I'm still fiddling with it but here's what it looks like at the moment:

![wip](https://cloud.githubusercontent.com/assets/3466341/14271379/90b2614e-fac6-11e5-8168-71e17ee89adb.png)

What do you think?

**Comment by ResidentMario** [comment]
Addressed in 3a5420e.

**Comment by neomatrix369** [comment]
@ResidentMario this dendogram feature is great but is there anything in the docs to explain this further and maybe with an example or two

**Comment by ResidentMario** [comment]
All of the documentation at the moment lives in [the README](https://github.com/ResidentMario/missingno#dendrogram).

Interpreting the dendrogram is a bit mathematically convoluted, so I never did write it up. 🙂
