### ISSUE TITLE
Could not reproduce heatmap from the README

### ISSUE THREAD

**Issue by rhiever** [ResidentMario/missingno#51]
I download and processed the collisions dataset using the notebook you link to in the README. I then fed that processed collisions dataset to the heatmap function (missingno v0.3.8) and this was my output:

![heatmap-error](https://user-images.githubusercontent.com/1719223/35602908-9d8ded6c-05ef-11e8-85ec-7f403e5f5959.png)

For some reason, the grid cells in the heatmap that don't have "significant" values aren't being masked. Happy to provide other package versions if that would be useful for debugging.

**Comment by ResidentMario** [comment]
I've been doing pretty extensive work on this library over the last few days, and I haven't run into this issue. It looks to me that the _masking_ is correct, but the colors are off: `0.2` corresponds with the most neutral color here, while _actual_ neutral values at 0.0 are assigned a darker red.

Do you still get this issue if you follow the new (significantly simpler data-wise) Quickstart?

Was this plot generated using `matplotlib 2.0`?

**Comment by rhiever** [comment]
```Python
In [1]: from matplotlib import __version__

In [2]: __version__
Out[2]: '2.1.2'
```

Looks like I'm reproducing the heatmap in the README fine now. Good work with the revised quickstart. One small request: Please take the `>>>` out of the code examples; I end up having to remove those in my notebook anyway.
