### ISSUE TITLE
README is too crowded - reorganize into a separate GitHub pages docs site

### ISSUE THREAD

**Issue by rhiever** [ResidentMario/missingno#54]
I suggest keeping the README short and to the point: badges showing status etc. of the package, what is the purpose of the package, how to install, 1-2 basic code examples, and contributing information.

More examples, function API docs, and detailed descriptions can be moved to the docs site.

I also suggest adding a gallery to the docs, [similar to Seaborn](https://seaborn.pydata.org/examples/index.html).

**Comment by ResidentMario** [comment]
I've split out the advanced configuration details in the `README.md` into a separate linked-to `CONFIGURATION.md` file in the repository, keeping the focus on the quickstart as much as possible. I won't do it right now, but yeah, maybe I'll set up a website for this repo eventually. I'll leave this issue open for nowc as a prompt to do so.
