### ISSUE TITLE
Histogram of data completeness by column

### ISSUE THREAD

**Issue by jbwhit** [ResidentMario/missingno#6]
First, great package! 

The data completeness shows the completeness of the data over *rows*, I'm requesting a way to show the data completeness over the *columns*. Maybe a sparkline/histogram below the bottom row? 

]

**Comment by ResidentMario** [comment]
Thanks; the response I've gotten on this project has been really great! This is another great idea for future work that's somewhat similar to #5. I think [dendrograms](http://i.stack.imgur.com/W17PL.png), bar charts, and sparklines should all be good options.

I'm reading up on how missing data imputation and visualization is handled in R to see what other visual ideas (and potentially new plots) I can incorporate into this project.

**Comment by ResidentMario** [comment]
OK, I've experimented with this and decided *against* implementing this feature.

The following code (plus changing some gridspec parameters) sets up a row completeness histogram, for reference.

This is due to the limitations of summing across 100 or more points in such a tiny space. Columns with very low numbers of values will be barely visible or, what's far worse, absent entirely---implying that there are **no** values in the column at all, when in fact there are simply so few that they don't make it to the draw screen!

So the result is misleading. A log axis option could perhaps circumvent this, but I decided that this is a level of complexity which defeats the purpose of the graphic in the first place.

        # column_completeness_srs = np.sum(df.notnull().astype(bool), axis=0)
        # x_domain = list(range(0, df.shape[1]))
        # y_range = column_completeness_srs.values / len(df)
        # ax2.bar(x_domain, y_range, color=(0.25, 0.25, 0.25), width=1, linewidth=0)
        # ax2.set_xlim([0, len(x_domain)])
        # ax2.set_ylim([1, 0])
        # ax2.set_aspect('auto')
        # ax2.grid(b=False)
        # ax2.xaxis.tick_top()
        # ax2.xaxis.set_ticks_position('none')
        # ax2.yaxis.set_ticks_position('none')
        # ax2.spines['top'].set_visible(False)
        # ax2.spines['right'].set_visible(False)
        # ax2.spines['bottom'].set_visible(False)
        # ax2.spines['left'].set_visible(False)
        # ax2.patch.set_visible(False)
        # ax2.set_xticks([])
        # ax2.set_yticks([])
        # in_between_point = [x for x in range(0, ex_df.shape[1])]
        # for in_between_point in in_between_point:
        #     ax2.axvline(in_between_point, linestyle='-', color='white')

**Comment by ResidentMario** [comment]
Note to self: once I finally write up a missing data tutorial be sure to build a pandas bar chart of data missingness as a part of that.

**Comment by ResidentMario** [comment]
@jbwhit As a follow-up I was thinking of implementing this as a separate plot. `pandas` seems to handle it pretty OK as-is.

Here's the plot:

     (data.isnull().sum() / len(data)).plot(kind='bar', figsize=(24, 10))

![plot](https://cloud.githubusercontent.com/assets/3466341/14908017/94b3ed18-0d9e-11e6-8f94-fca3abb305d5.png)

Even with much more screen space the problem of interpreting those almost-but-not-quite-always-filled values remains. A log axis helps, but makes the result harder to interpret as well.

I wonder what the happy medium is...so I'm still thinking about this one.

**Comment by ankostis** [comment]
Please reconsider your decision.  
And indeed a log-scale would make bra-plot highly readable.

Thanks, anyway, for your efforts!

**Comment by ResidentMario** [comment]
If people feel strongly enough about this to warrant commenting on a closed issue... I wonder if I couldn't use the solution for #9, apply a label to the display.

It would probably be best to implement this as a separate chart type.

**Comment by ankostis** [comment]
I tried to workaround it by using with your code, above, after the invocation to `matrix()`,
but since the creation of the figure/subplots happens internally, I didn't manage to create a proper bottom axis.

**Comment by ResidentMario** [comment]
Not sure the issue might be that there was an API change in the intervening time. But, that is a starting point.

**Comment by ResidentMario** [comment]
Addressed in 6bb8294575ffba85a6489d920e0e4598db9b3e84. A new chart type has been added, `msno.bar`, which works as described:


![image](https://cloud.githubusercontent.com/assets/3466341/19700733/7658f93e-9ac6-11e6-9ee6-679b0786e849.png)

A `log` option is included.

This is live now as a part of the [`0.3.0` release](https://github.com/ResidentMario/missingno/releases/tag/0.3.0) (`pip install -U missingno` to get it).

I have not added this as an option to the `matrix` display, maybe that's something to consider down the road.
