### ISSUE TITLE
Fail to install missingno via Command Line

### ISSUE THREAD

**Issue by pakkiy** [ResidentMario/missingno#68]
I tried to install via command line, and get the following error: 
Could not find a version that satisfies the requirement pyarrow<0.8.0,>=0.4.0 (from quilt) (from versions: )
No matching distribution found for pyarrow<0.8.0,>=0.4.0 (from quilt)Could not find a version that satisfies the requirement pyarrow<0.8.0,>=0.4.0 (from quilt) (from versions: )
No matching distribution found for pyarrow<0.8.0,>=0.4.0 (from quilt)

May I know why?

**Comment by ResidentMario** [comment]
What command are you running? `quilt` is not a package dependency:

    install_requires=['numpy', 'matplotlib', 'scipy', 'seaborn']

I assume you mean that you're trying to run `pip install quilt`, as per the Quickstart instructions, and it's failing.

Can you post what your environment is? I mean the output of `pip list` or `conda list`.
