### ISSUE TITLE
Show only a subset of columns

### ISSUE THREAD

**Issue by Moisan** [ResidentMario/missingno#7]
I sometime work with large DataFrame tables coming from databases and the number of columns  (for example, over a hundred columns) make the missingno graphic hard to analyze. I propose to add a feature that allow to select the top n most/less populated columns (or top/bottom n%). I guess this would be somewhat related to #5 since both are based on column statistics.

Another approach could be to show only the columns where n% of the rows (don't) have missing data.

**Comment by ResidentMario** [comment]
This is a good feature idea!

**Comment by ResidentMario** [comment]
Addressed in 3a5420e.
