### ISSUE TITLE
Installing the package

### ISSUE THREAD

**Issue by filipposebastio** [ResidentMario/missingno#70]
Apologies, I am new to python and this is a very basic request. I'd love to use your tool, but I am struggling with the installation:

I installed Quilt correctly using py -m install quilt, but when I run from python

import quilt
quilt.install("ResidentMario/missingno_data")
from quilt.data.ResidentMario import missingno_data
import missingno_data as msno

i get ModuleNotFoundError: No module named 'missingno_data'

why?

**Comment by ResidentMario** [comment]
This codeline relies on the Quilt service, which may have experienced a transient network failure. Does it work if you try again now?

**Comment by ResidentMario** [comment]
Ah, actually, on re-reading what you did, here's your error:

```python
import missingno_data as msno
```

Should be:

```python
import missingno as msno
```
