### ISSUE TITLE
What does the right Y axis ticks in missingno represent?

### ISSUE THREAD

**Issue by aguinaldoabbj** [ResidentMario/missingno#73]
According to the example run by the author in the docs, I thought Y axis represented the number of entries according to the percentage in the right Y axis. However, values are way discrepant in my case:

![screenshot_20180717_094403](https://user-images.githubusercontent.com/13151704/42817974-093674f0-89a6-11e8-92a8-b6dd2203ac37.png)

Could anyone explain what the right Y axis ticks really represent?

**Comment by ResidentMario** [comment]
Can you still reproduce this issue? I believe there was an issue in an earlier version of `missingno` involving tick offsets that caused this behavior, but it was fixed in the last version.
