### ISSUE TITLE
Sparkline in msno.matrix

### ISSUE THREAD

**Issue by divyansha** [ResidentMario/missingno#74]
According to the documentation, 'The sparkline at right summarizes the general shape of the data completeness and points out the maximum and minimum rows.'

What does 'general shape of data completeness' mean? And how are 'maximum and minimum rows' defined?

**Comment by ResidentMario** [comment]
> the general shape of the data completeness

It tells you where in the dataset, row-wise, the empty or `nan` values are. Assuming the data in the dataset is IID this isn't meaningful, but it can be important in cases where locality matters, like e.g. certain time series datasets.

> maximum and minimum rows

Maximum and minimum in terms of nullity. Agree that this is a little bit cut up, I've updated the documentation slightly to better explain this.
