### ISSUE TITLE
adjust plot size

### ISSUE THREAD

**Issue by angelatcp** [ResidentMario/missingno#75]
how do you adjust the size of the layout in msno.matrix? the labels at the top are cut off even though they have lesser number of characters than your example. please assist

**Comment by ResidentMario** [comment]
Try using [`figsize`](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.figure.html) (e.g. `msno.matrix(df, figsize=(20, 20))`. It would be helpful if you attached a screenshot, not much I can do without seeing what the exact issue is.

**Comment by angelatcp** [comment]
perfect, figsize helps to do that so my labels can fit within the figure size. i have also adjusted the font size (eg. msno.matrix(df, figsize=(20,20), fontsize=20)) but it only adjusted the font size for the x-axis labels and not the y-axis labels as well as the numbers on the right side (showing minimum number of missing column and maximum missing number of columns for the entry). 

would you be able to advise how to adjust the font size for the y-axis label and the numbers on the right side of the plot? thanks!

**Comment by ResidentMario** [comment]
Uselessly late but the plot is managed in terms of subplots, and you can adjust the other variables by asking for the specific subplot of interest and then modifying it. cf. https://matplotlib.org/api/_as_gen/matplotlib.pyplot.subplots.html
