### ISSUE TITLE
Fontsize not applied to y-axis' nor min/max labels in 'matrix' plot

### ISSUE THREAD

**Issue by CacahueteNC** [ResidentMario/missingno#76]
Hi, first thanks for the good work and for sharing it.

It appears that the ```matrix()``` function do not make use of its ```fontsize``` argument when creating the ```set_yticklabels``` and min/max annotations. ```fontsize``` for these items is respectively hardcoded to ```20``` and ```14```.

See[ line 113](https://github.com/ResidentMario/missingno/blob/f190bd6f761761831f5d34308d7436566fcbe16f/missingno/missingno.py#L113),[ line 116](https://github.com/ResidentMario/missingno/blob/f190bd6f761761831f5d34308d7436566fcbe16f/missingno/missingno.py#L116), [line 172](https://github.com/ResidentMario/missingno/blob/f190bd6f761761831f5d34308d7436566fcbe16f/missingno/missingno.py#L172) and[ line 178](https://github.com/ResidentMario/missingno/blob/f190bd6f761761831f5d34308d7436566fcbe16f/missingno/missingno.py#L178)

Thank in advance for your review.

**Comment by ResidentMario** [comment]
Font sizes are now scaled against the `fontsize` parameter throughout. Thanks for the report.
