### ISSUE TITLE
Anaconda issue

### ISSUE THREAD

**Issue by carlos-pereyra** [ResidentMario/missingno#78]
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]

`>>> import pandas as pd`
`>>> import numpy as np`
`>>> null_pattern = (np.random.random(1000).reshape((50, 20)) > 0.5).astype(bool)`
`>>> null_pattern = pd.DataFrame(null_pattern).replace({False: None})`
`>>> import missingno as msno`
`>>> msno.matrix(null_pattern.set_index(pd.period_range('1/1/2011', '2/1/2015', freq='M')) , freq='BQ')`

Error:

2018-11-23 17:27:11.366 python[90523:11846379] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7ff846696880
2018-11-23 17:27:11.375 python[90523:11846379] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7ff846696880'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff4f27732b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff768e1c76 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4f30fe04 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff4f1ed870 ___forwarding___ + 1456
	4   CoreFoundation                      0x00007fff4f1ed238 _CF_forwarding_prep_0 + 120
	5   Tk                                  0x00007fff5b90d318 TkpInit + 467
	6   Tk                                  0x00007fff5b88c252 Tk_Init + 1710
	7   _tkinter.cpython-36m-darwin.so      0x000000011cfe6da4 Tcl_AppInit + 84
	8   _tkinter.cpython-36m-darwin.so      0x000000011cfe6a7b _tkinter_create + 1115
	9   libpython3.6m.dylib                 0x000000010bf73a81 _PyCFunction_FastCallDict + 497
	10  libpython3.6m.dylib                 0x000000010bff5787 call_function + 439
	11  libpython3.6m.dylib                 0x000000010bff1f62 _PyEval_EvalFrameDefault + 27346
	12  libpython3.6m.dylib                 0x000000010bff61ef _PyEval_EvalCodeWithName + 2447
	13  libpython3.6m.dylib                 0x000000010bff6d92 _PyFunction_FastCallDict + 738
	14  libpython3.6m.dylib                 0x000000010bf2b677 _PyObject_FastCallDict + 247
	15  libpython3.6m.dylib                 0x000000010bf2b795 _PyObject_Call_Prepend + 149
	16  libpython3.6m.dylib                 0x000000010bf2b4b0 PyObject_Call + 96
	17  libpython3.6m.dylib                 0x000000010bf8baed slot_tp_init + 125
	18  libpython3.6m.dylib                 0x000000010bf87e29 type_call + 313
	19  libpython3.6m.dylib                 0x000000010bf2b645 _PyObject_FastCallDict + 197
	20  libpython3.6m.dylib                 0x000000010bf2ba75 _PyObject_FastCallKeywords + 197
	21  libpython3.6m.dylib                 0x000000010bff5688 call_function + 184
	22  libpython3.6m.dylib                 0x000000010bff2001 _PyEval_EvalFrameDefault + 27505
	23  libpython3.6m.dylib                 0x000000010bff69ed fast_function + 381
	24  libpython3.6m.dylib                 0x000000010bff5761 call_function + 401
	25  libpython3.6m.dylib                 0x000000010bff1f62 _PyEval_EvalFrameDefault + 27346
	26  libpython3.6m.dylib                 0x000000010bff61ef _PyEval_EvalCodeWithName + 2447
	27  libpython3.6m.dylib                 0x000000010bff6d92 _PyFunction_FastCallDict + 738
	28  libpython3.6m.dylib                 0x000000010bf2b677 _PyObject_FastCallDict + 247
	29  libpython3.6m.dylib                 0x000000010bf2b795 _PyObject_Call_Prepend + 149
	30  libpython3.6m.dylib                 0x000000010bf2b4b0 PyObject_Call + 96
	31  libpython3.6m.dylib                 0x000000010bff2245 _PyEval_EvalFrameDefault + 28085
	32  libpython3.6m.dylib                 0x000000010bff61ef _PyEval_EvalCodeWithName + 2447
	33  libpython3.6m.dylib                 0x000000010bff6a91 fast_function + 545
	34  libpython3.6m.dylib                 0x000000010bff5761 call_function + 401
	35  libpython3.6m.dylib                 0x000000010bff2001 _PyEval_EvalFrameDefault + 27505
	36  libpython3.6m.dylib                 0x000000010bff61ef _PyEval_EvalCodeWithName + 2447
	37  libpython3.6m.dylib                 0x000000010bff6a91 fast_function + 545
	38  libpython3.6m.dylib                 0x000000010bff5761 call_function + 401
	39  libpython3.6m.dylib                 0x000000010bff2001 _PyEval_EvalFrameDefault + 27505
	40  libpython3.6m.dylib                 0x000000010bff61ef _PyEval_EvalCodeWithName + 2447
	41  libpython3.6m.dylib                 0x000000010bfeb3d4 PyEval_EvalCode + 100
	42  libpython3.6m.dylib                 0x000000010c020bd6 PyRun_InteractiveOneObject + 582
	43  libpython3.6m.dylib                 0x000000010c02050e PyRun_InteractiveLoopFlags + 222
	44  libpython3.6m.dylib                 0x000000010c0203fc PyRun_AnyFileExFlags + 60
	45  libpython3.6m.dylib                 0x000000010c039835 Py_Main + 3829
	46  python                              0x000000010bf19df8 main + 232
	47  libdyld.dylib                       0x00007fff774fb015 start + 1
	48  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by ResidentMario** [comment]
Works on my machine. It looks like you have some sort of low-level C library failures, are you sure your Python is configured correctly?

**Comment by carlos-pereyra** [comment]
> Works on my machine. It looks like you have some sort of low-level C library failures, are you sure your Python is configured correctly?

Yes, you were right. Apparently something happened to matplotlib when I installed anaconda. I had to had to create matplotlibrc file and add 'backend: TkAgg'.

**Comment by ResidentMario** [comment]
Sounds good.
