### ISSUE TITLE
Legend in heatmap

### ISSUE THREAD

**Issue by mattharrison** [ResidentMario/missingno#80]
I did a heatmap on the titanic dataset and it is a little hard to interpret. Some of the cells have numbers in them while others don't. I have no idea what the colors represent as there is no legend to interpret them.

![screen shot 2018-12-06 at 6 04 52 pm](https://user-images.githubusercontent.com/119405/49621228-8b6bdf00-f981-11e8-823f-36aafcd238bb.png)

**Comment by ResidentMario** [comment]
> Some of the cells have numbers in them while others don't.

Numbers are nullity correlation scores scaled in the range [-1, 1]. Cells without numbers in them score close to 0, e.g. have confidently completely random nullity correlations. It would be tedious to interpret a plot with a lot of 0 scores so the visualization leaves them out.

In general, for matters of interpretation, the [corresponding `README.md` section](https://github.com/ResidentMario/missingno#heatmap) should be sufficient.

> I have no idea what the colors represent as there is no legend to interpret them.

A legend is not a bad feature to add. But I think that once you know what the scores mean, you *do* know what the colors mean. Stronger red means stronger negative correlation, and stronger blue (not present here) means stronger positive correlation. 🙂

**Comment by mattharrison** [comment]
Thanks for your response. 

Consider my point of view (been doing ML for years) as someone fresh to your project and your's as the developer (you know the code inside and out) are probably not seeing the results as someone new to the project would. You understand the plot and it makes intuitive sense to you. To me it is not interpretable. Even after going through the README. If it weren't for the numbers, I would say that boat and body are highly (pos or neg) correlated, much more than boat and home.dest. I would venture to guess that most people new to your project would have a similar reaction to mine with this plot.

I don't want to have to read the README to interpret the heatmap. A good visualization should stand on its own. If I'm going to include it in a slideshow, I want it to be self-explanatory. A legend would greatly assist that. At the very least it should be an option.

I'm not trying to be negative. I think the project is awesome, and I love the other plots. I think a few small tweaks would be really beneficial to others who would like to take advantage of your project!

**Comment by ResidentMario** [comment]
> To me it is not interpretable. Even after going through the README.

Fair enough, I can add a legend feature to the plot.

**Comment by mattharrison** [comment]
In my local copy I added this by updating the signature to:

    def heatmap(df, inline=False,
            filter=None, n=0, p=0, sort=None,
            figsize=(20, 12), fontsize=16, labels=True, cmap='RdBu',
            cbar=False
            ):

and in the body added the cbar, vmin, and vmax arg:

    if labels:
        sns.heatmap(corr_mat, mask=mask, cmap=cmap, ax=ax0, cbar=cbar,
                    annot=True, annot_kws={'size': fontsize - 2},
                    vmin=-1, vmax=1)
    else:
        sns.heatmap(corr_mat, mask=mask, cmap=cmap, ax=ax0, cbar=cbar,
                    vmin=-1, vmax=1)

Would love to get this committed as I'm currently writing a book and would like to include this library in the book ;)

**Comment by ResidentMario** [comment]
😅 I'll look into it this weekend.

**Comment by ResidentMario** [comment]
This is fixed on `master`. Some behavioral changes to `heatmap`:

* The colorscale is now pinned to -1, 1 by default. This aids interpretability, since the color scale will now always be smoothed out and pinned. However, it also decreases the effective color range in the relevant part of your data (e.g. your nullity is unlikely to scale _fully_ between those values). The new `vmin` and `vmax` parameters can be used to control this normalization.
* The colorbar is now displayed by default. You can omit it with `cbar=False`.

It may be a few more days before I release to PyPI.
