### ISSUE TITLE
Problem exporting to PDF

### ISSUE THREAD

**Issue by aguinaldoabbj** [ResidentMario/missingno#81]
When using msno.matrix() and trying to export to pdf using matplotlib:

`fig.savefig('fig1.pdf', format='pdf', bbox_inches='tight')`

I get a pdf file with a empty plot. All font components appears normally, as ticks, labels, titles, etc. But the plot itself is blank, as can be seen in the attached figure.

![screenshot_20190109_102830](https://user-images.githubusercontent.com/13151704/50902365-760f2800-13f9-11e9-8ae8-64c4ded0cab7.png)

**Comment by ResidentMario** [comment]
I've found exporting to PDF to be extremely finicky. When I had a similar problem with `geoplot`, adding a `pad_inches=0.1` parameter solved it. Does that help?

**Comment by aguinaldoabbj** [comment]
> I've found exporting to PDF to be extremely finicky. When I had a similar problem with `geoplot`, adding a `pad_inches=0.1` parameter solved it. Does that help?

No, it didn't. I've tested with matplotlib version 2.2.2 and 3.0.2.

**Comment by ResidentMario** [comment]
I was unable to reproduce your problem. The following code worked as expected:

```python
import missingno as msno
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(42)

fig = plt.Figure()
msno.matrix(
    pd.DataFrame(
        (np.random.random((1000, 10)) > 0.2)
    ).replace(False, np.nan)
)

fig = plt.gcf()
fig.savefig('temp.pdf', format='pdf', bbox_inches='tight')

from IPython.display import IFrame
IFrame("temp.pdf", width=800, height=500)
```

Using `matplotlib==3.0.2`.

Can you provide an [MVP](https://stackoverflow.com/help/mcve) of this not working, as well as your environment definition?
