### ISSUE TITLE
Data labels missing on x-axis

### ISSUE THREAD

**Issue by sumnayak** [ResidentMario/missingno#93]
Hello,

The labels for the column names don't appear on the x-axis when I use bar and matrix plots. I tried this using Jupyter notebook, on Python 3.
I tried copying off someone else's notebook; this person has used the same code as the snippets below. They were able to print the column names, but I wasn't.

I did this on terminal first:

```
$ pip install quilt
$ quilt install ResidentMario/missingno_data
```

And then

```
%matplotlib inline
from quilt.data.ResidentMario import missingno_data as msno
msno.bar(df_train.sample(300))
msno.matrix(df_train.sample(300))
```

Bar chart:
![Unknown](https://user-images.githubusercontent.com/49649355/61404608-c9c96500-a8a5-11e9-981f-fec886e51bdb.png)

Matrix chart:
![Unknown](https://user-images.githubusercontent.com/49649355/61404584-bfa76680-a8a5-11e9-955b-0f7bdce08462.png)

**Comment by ResidentMario** [comment]
This is actually a feature! If you pass a dataset with more than fifty columns to `missingno`, the labels will default to off. The opposite is true if you pass a dataset with fewer than fifty columns.

The fifty-column breakpoint is somewhat arbitrary, but the problem it solves is not: large datasets with many, many columns would have labels that are too small to be readable, or which would collide with one another's bounding boxes, becoming gibberish.

[Here's the exact code that implements this behavior](https://github.com/ResidentMario/missingno/blob/1c69ec987ef88878abc1bfa15f95d66aa513075d/missingno/missingno.py#L83). As you can see, you can override this behavior by manually specifying `labels=True`. For instance, change this:

```python
%matplotlib inline
from quilt.data.ResidentMario import missingno_data as msno
msno.bar(df_train.sample(300))
msno.matrix(df_train.sample(300))
```

To this:

```python
%matplotlib inline
from quilt.data.ResidentMario import missingno_data as msno
msno.bar(df_train.sample(300), labels=True)
msno.matrix(df_train.sample(300), labels=True)
```

Hope that's helpful.

**Comment by sumnayak** [comment]
That worked! Thank you so much

**Comment by blossomgirl96** [comment]
thanks!

**Comment by MeetPatel41011** [comment]
Thank a lot! ✨
