### ISSUE TITLE
vmin/vmax argument of heatmap() does not seem to have an effect + throws error

### ISSUE THREAD

**Issue by moritzkoerber** [ResidentMario/missingno#95]
Hi, 
according to the source code, the color scale of heatmap() is automatically adjusted to range from -1 to 1 by vmin/vmax. However, this does not seem to work. My data set features correlations only down to -0.1, but they are marked in deep red. 

Setting the parameters explicitly throws an error:

```
heatmap(df, vmin = -1, vmax = 1)

> heatmap() got an unexpected keyword argument 'vmin'
```
The visualization is fine if I add an artificial correlation of -.99. I am using matplotlib 3.1.0

**Comment by ResidentMario** [comment]
I can't reproduce this error. The follow code works for me with `matplotlib@3.1.1`:

```python
import pandas as pd

np.random.seed(42)
simple_df = pd.DataFrame(
    (np.random.random((20, 10)) > 0.5), columns=range(0, 10)
).replace(False, np.nan)
large_df = pd.DataFrame(
    (np.random.random((250, 60)) > 0.5)
).replace(False, np.nan)

import missingno as msno
import matplotlib.pyplot as plt

msno.heatmap(simple_df, vmin=-1, vmax=1)
```

**Comment by moritzkoerber** [comment]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-a43b2ee1587c> in <module>
     13 import matplotlib.pyplot as plt
     14 
---> 15 msno.heatmap(simple_df, vmin=-1, vmax=1)

TypeError: heatmap() got an unexpected keyword argument 'vmin'


Run in JupyterLab 1.0.2 and Spyder 3.3.6, same error both times. missgno version is 0.4.1 and my python environment is

          conda version : 4.7.10
    conda-build version : 3.18.9
         python version : 3.7.3.final.0

**Comment by ResidentMario** [comment]
The `vmin` and `vmax` arguments were added in `missingno` version `0.4.2` (in response to [this GH issue](https://github.com/ResidentMario/missingno/issues/80#issuecomment-464297098), the current release; they were absent in version `0.4.1`, which is the version you are using. To get the new plot behavior, upgrade the package via `pip install -U missingno`.
