### ISSUE TITLE
QuickStart notebook doesn't display examples

### ISSUE THREAD

**Issue by pedugnat** [ResidentMario/missingno#96]
The QuickStart notebook doesn't render the plots, maybe you have to rerun it so that the notebook displays it.
https://github.com/ResidentMario/missingno/blob/master/QuickStart.ipynb

**Comment by datatalking** [comment]
Hi @pedugnat If you click the "Quickstart Binder" link about 1/3rd of the way down the page it will open a binder notebook. About two minutes later the Jupiter notebook will open. From there you just click run for each cell you want to activate, but to run them all click "cell" above the word "Run" and select "Run All"
