### ISSUE TITLE
Suggest adding hyphen to repo description: "Missing-data visualization..."

### ISSUE THREAD

**Issue by bskinn** [ResidentMario/missingno#99]
This is a minor thing, but without that hyphen there I initially read the Github repo description as meaning more of a marketing-hype 'this is the data visualization module that Python has been missing!!!' instead of the plainly descriptive 'this is a Python module for visualizing missing data'.

**Comment by ResidentMario** [comment]
I don't think I've ever seen it refered to as "missing-data", so I propose
that that would be a bad idea on semantic grounds. :)

**Comment by bskinn** [comment]
Oh, for sure - if it's just by itself as a noun, then it's "missing data", as in: "I noticed a bunch of missing data."

But when the phrase is modifying something else, per [English grammar rules](https://www.grammarly.com/blog/hyphen-with-compound-modifiers/) it gets hyphenated to clarify what's part of the modifier and what's part of what's being modified... e.g., "We have a huge missing-data problem" (distinguishing 'We have a huge problem with missing data' from 'We have a data problem that is huge and missing'.)

As I said in OP, it's definitely a minor thing -- but it made me significantly misread your tagline when I first saw it.

Still will very likely try out the tool, though -- I can think of some past work where it would've come in really handy!
